import type { IFormatter } from "./base";
import type { ReviewSession } from "../types/review";
import type { Finding } from "../types/agent";

const SEVERITY_EMOJI: Record<string, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🔵",
  info: "⚪",
};

export const markdownFormatter: IFormatter = {
  name: "markdown",
  mimeType: "text/markdown",
  fileExtension: ".md",

  format(session: ReviewSession): string {
    const lines: string[] = [];
    const d = new Date(session.createdAt).toLocaleString();

    lines.push(`# Code Review Report`);
    lines.push(`\n*Reviewed ${d} · Level: \`${session.request.level}\` · ${session.durationMs}ms*\n`);
    lines.push(`## Summary\n\n${session.summary}\n`);

    if (session.routerDecision) {
      lines.push(`<details><summary>Router Decision</summary>\n`);
      lines.push(`**Agents selected:** ${session.routerDecision.selectedAgents.join(", ")}`);
      lines.push(`\n**Skills activated:** ${session.routerDecision.selectedSkills.join(", ") || "none"}`);
      lines.push(`\n**Rationale:** ${session.routerDecision.rationale}`);
      lines.push(`\n</details>\n`);
    }

    if (session.findings.length === 0) {
      lines.push(`## Findings\n\n✅ No issues found.\n`);
      return lines.join("\n");
    }

    lines.push(`## Findings\n`);

    const bySeverity = groupBySeverity(session.findings);
    for (const severity of ["critical", "high", "medium", "low", "info"]) {
      const items = bySeverity[severity] ?? [];
      if (items.length === 0) continue;

      lines.push(`### ${SEVERITY_EMOJI[severity]} ${capitalize(severity)} (${items.length})\n`);
      for (const f of items) {
        const location = f.filePath
          ? ` · \`${f.filePath}${f.lineStart ? `:${f.lineStart}` : ""}\``
          : "";
        lines.push(`#### ${f.title}${location}`);
        lines.push(`\n**Category:** ${f.category}${f.skillId ? ` · Skill: \`${f.skillId}\`` : ""}`);
        lines.push(`\n${f.description}`);
        lines.push(`\n**Suggestion:** ${f.suggestion}\n`);
      }
    }

    lines.push(`\n---\n*Generated by [review-harness](https://github.com/review-harness) · Tokens used: ${session.totalTokensUsed}*`);
    return lines.join("\n");
  },
};

function groupBySeverity(findings: Finding[]): Record<string, Finding[]> {
  const result: Record<string, Finding[]> = {};
  for (const f of findings) {
    if (!result[f.severity]) result[f.severity] = [];
    result[f.severity]!.push(f);
  }
  return result;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
